import { Dimensions, StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: {
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  searchContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  flex: 1,
  marginLeft: 10,
  backgroundColor: COLORS.backgroundLight,
  borderRadius: 8,
  paddingHorizontal: 8,
  height: 40,
},

searchInput: {
  flex: 1,
  color: COLORS.textLight,
  paddingHorizontal: 8,
  fontSize: 16,
},

  headerTitle: { fontSize: 18, fontWeight: '700', color: COLORS.textLight },
  contentArea: { flex: 1, flexDirection: 'row' },
  mainCategoriesSidebar: {
    width: Dimensions.get('window').width * 0.35,
    backgroundColor: COLORS.card,
    borderRightWidth: 1,
    borderRightColor: COLORS.placeholder + '20',
  },
  mainCategoryTab: {
    paddingVertical: 15,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftWidth: 3,
    borderLeftColor: 'transparent',
  },
  mainCategoryTabSelected: { backgroundColor: COLORS.background, borderLeftColor: COLORS.primary },
  mainCategoryText: { fontSize: 12, marginTop: 5, fontWeight: '500', color: COLORS.textDark, textAlign: 'center' },
  mainCategoryTextSelected: { fontWeight: '700', color: COLORS.primary },
  subCategoriesContent: { flex: 1, padding: 10 },
  subContentTitle: { fontSize: 18, fontWeight: '800', color: COLORS.textDark, marginBottom: 15, paddingLeft: 5 },
  subCategoryGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-start' },
  subCategoryCard: {
    width: Dimensions.get('window').width * 0.3 - 20,
    margin: 5,
    padding: 10,
    backgroundColor: COLORS.card,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: COLORS.textDark,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  subCategoryCardImagePlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.primary + '10',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  subCategoryCardText: { fontSize: 11, fontWeight: '600', color: COLORS.textDark, textAlign: 'center' },
  footerNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 10,
    backgroundColor: COLORS.card,
    borderTopWidth: 1,
    borderTopColor: COLORS.placeholder + '30',
  },

  footerNavItem: { alignItems: 'center', flex: 1 },
  footerNavText: { fontSize: 10, marginTop: 4, fontWeight: '600', color: COLORS.secondary },
});
